### ISSUE TITLE
Funding links out-of-order

### ISSUE THREAD

**Issue by colinodell** [composer/packagist#1077]
Commit 54fcb5016afa8b2035d8cd1537cc0fea2cab11ba changes the order of funding links to something other than the author's preferred sort order (as provided in either their `composer.json` or `FUNDING.yml` file).

As a result, my funding sources display in this order:

![image](https://user-images.githubusercontent.com/202034/78845019-6eac4500-79d5-11ea-8efd-8a1fd00ca165.png)

Whereas my FUNDING.yml file uses this order:

```yml
github: colinodell
patreon: colinodell
tidelift: packagist/league%2fcommonmark
custom: ["https://www.colinodell.com/sponsor", "https://www.paypal.me/colinpodell/10.00", "https://enjoy.gitstore.app/repositories/thephpleague/commonmark"]
```

Because GitHub is offering to match sponsorships, I would prefer to have that link show first.  Having Packagist respect my preferred order would be the easiest way to accomplish this.

GitHub (of course) puts their Sponsor program first, but at least it respects my `custom` options:

![image](https://user-images.githubusercontent.com/202034/78845047-8257ab80-79d5-11ea-9f23-3765b5743a42.png)

## Potential Solutions

Would any of these potential solutions be feasible?

1. Revert 54fcb5016afa8b2035d8cd1537cc0fea2cab11ba if the impact isn't too significant
2. Only perform the sorting when generating metadata (instead of pre-sorting it and losing that sort order)
3. Store the original sort order in the database and use that on the Packagist.org frontend (perhaps store a third `sort_order` key in the JSON, strip it out when generating metadata, or re-sort by this when using on the frontend, or just store the sorted data in an additional field)
