### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by agargiulo** [composer/packagist#710]
You can set up your own install of packagist by cloning this repo and following the README, great :+1:  
And there is a section in `config/parameters.yml` that allows you to configure github things:

``` yaml
    # set those to values obtained by creating an application at https://github.com/settings/applications
    github.client_id: CHANGE_ME_IN_PROD
    github.client_secret: CHANGE_ME_IN_PROD
```

But there isn't a place to set the URL for github so it would be nice if we could configure it for GHE
