### ISSUE TITLE
Packagist in Docker

### ISSUE THREAD

**Issue by f3l1x** [composer/packagist#779]
Hi. 

First of all, I would like to say thank you on packagist. I was looking for a way how to help you / me / companies to run their own private packagist. It was in the time before packagist.com. Toran proxy is quite good, but if you have more ten 10 packages and many versions you need something more.

Here you go :dog2: 

I've created a tiny set of containers (app[nginx+php7.1+fpm+cron], solr, redis) for smooth running of Packagist in Docker. 

You can find it here: https://github.com/dockette/packagist

Example of docker-compose.yml.

```yaml
version: '2'

services:

  packagist:
    restart: always
    image: dockette/packagist:app

    ports:
      - 80:8000

    environment:
      - PACKAGIST_DATABASE_USER=packagist
      - PACKAGIST_DATABASE_PASSWORD=packagist
    
    depends_on:
      - mysql
      - redis
      - solr

  mysql:
    restart: always
    image: mariadb:10.1

    volumes:
      - ./data/mysql:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=packagist
      - MYSQL_USER=packagist
      - MYSQL_PASSWORD=packagist

  redis:
    restart: always
    image: redis:3.2

    volumes:
      - ./data/redis:/data

  solr:
    image: dockette/packagist:solr

    volumes:
      - ./data/solr:/opt/solr/server/solr/mycores
```

I hope it might be helpful for someone who needs to run own packagist and also for someone who wants to try docker. 

I appreciate your feedback. :sparkles: 

Thank you.
Felix
